# github.com/robot007num/go/bbs Global Configuration

# jwt configuration
jwt:
  signing-key: robot007num
  rexpires-time: 2  #hour
  aexpires-time: 1  #hour
  issuer: robot007num

# zap logger configuration
zap:
  level: info
  format: json
  prefix: ""
  director: log
  show-line: false
  encode-level: LowercaseLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
  max-age: 7
  size: 10
  back_up:  1
  compress: true

# system configuration
system:
  env: public # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: mysql
  use-redis: false # 使用redis
  use-multipoint: false
  router-prefix: "" #  路由全局前缀

# mysql connect configuration
mysql:
  host: "localhost"
  port: 3306
  config: ""
  db-name: "BBS_Data"
  username: "root"
  password: "root"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

# redis configuration
redis:
  db: 0
  addr: 127.0.0.1:6800
  password: ""